# This is a basic workflow to help you get started with Actions

name: Build base image

on:
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: ENV
        run: |
          echo "REPO_NAME=${{ github.event.repository.name }}" >> $GITHUB_ENV
          echo "TAG=1.0.0" >> $GITHUB_ENV
          echo "DOCKER_IMAGE=tercen/${{ github.event.repository.name }}_base" >> $GITHUB_ENV
      - name: Build docker image
        run: |
          docker build -t $DOCKER_IMAGE:$TAG base-image
      - name: docker login
        run: |
          docker login --username ${{ secrets.DOCKER_HUB_USERNAME }} --password ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: docker push
        run: |
          docker push $DOCKER_IMAGE:$TAG